name: CI

on:
  push:
    branches:
      - main
      - develop
      - '*'
  pull_request:

concurrency:
  group: dialogdrive-ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    name: Lint / Type Check / Audit
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Run lint suite
        run: npm run lint

      - name: Website lint
        run: npm run lint:website

      - name: npm audit (high severity, prod deps)
        run: npm audit --omit=dev --audit-level=high

  unit:
    name: Vitest Unit Suite
    needs: lint
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Run unit tests with coverage
        run: npm run test:unit

      - name: Upload vitest coverage
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: vitest-coverage
          path: |
            reports/coverage
            reports/vitest-junit.xml
          if-no-files-found: ignore

  e2e:
    name: Playwright Smoke
    needs: unit
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Cache Playwright browsers
        uses: actions/cache@v4
        with:
          path: ~/.cache/ms-playwright
          key: playwright-browsers-${{ runner.os }}-${{ hashFiles('package-lock.json') }}

      - name: Install Playwright browsers
        run: npx playwright install --with-deps chromium

      - name: Build extension bundle
        run: npm run build

      - name: Run smoke suite
        env:
          DD_SKIP_REBUILD: '1'
        run: xvfb-run --auto-servernum -- npm run test:e2e:smoke

      - name: Upload Playwright artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-results
          path: |
            playwright-report
            test-results
          if-no-files-found: ignore
